services:
    portunus:
        image: portunus:latest
        container_name: portunus
        build:
            context: .
            dockerfile: Dockerfile
            no_cache: true

        # access to Docker daemon
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

        environment:
            - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
